queue_rules:
  - name: default
    conditions:
      - check-success=build

pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "status-success=build"
    actions:
      queue:
        method: merge
        name: default
  - name: Merge scala-steward
    conditions:
      - base=master
      - author=scala-steward
      - "status-success=build"
    actions:
      queue:
        method: merge
        name: default
